version: "3"
services:
  nginx:
    image: tryan225/kramericaindustries:1.0
    container_name: nginx-simple
    restart: always
    network_mode: "bridge"
    ports:
      - 8080:80
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:kramericaindustries.net
      - traefik.port=80
      - traefik.docker.network=web

networks:
  web:
    external: true